#!/bin/zsh

. ~/.zsh/vars

alias mv='mv -v'
alias mmv='noglob zmv -W'
alias rm='rm -iv'
alias cp='cp -v'
alias mplayer='mplayer -idx'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'

alias c='clear'
alias ll='ls -ahl | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
alias ls='ls -GF'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='mirage'
# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}='mplayer -idx'
# auto open audio
alias -s {mp3,ogg,wav,flac}='cmus'
# auto open web addresses
alias -s {html,php,com,net,org,gov}='firefox'
# auto open regular files
alias -s txt='vim'
alias -s pdf='xpdf'

alias wcat='wget -q -O -'
alias svim='sudo vim'
alias sv='svim'
alias v='mvim'
alias cmake='cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc'
alias hosteurope='ssh root@83.169.21.36'
#alias esltv='/home/gig/downloads/octoshape/OctoshapeClient -url:ESL.oph350'
#alias esltv2='/home/gig/downloads/octoshape/OctoshapeClient -url:tetv.cebit1'
alias run='open -a'
