#!/bin/zsh

. ~/.zsh/vars

alias mv='mv -v'
alias mmv='noglob zmv -W'
alias rm='rm -iv'
alias cp='cp -v'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'
alias c='clear'
alias ll='ls -ahl | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
alias ls='ls -GF'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='open -a Preview'
# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}='open -a MPlayer\ OSX\ Extended'
# auto open audio
alias -s {mp3,ogg,wav,flac}='open -a Winamp'
# auto open web addresses
alias -s {html,php,com,net,org,gov}='open -a Chromium'
# auto open regular files
alias -s txt='vim'
alias -s pdf='open -a Preview'

alias mplayer='mplayer -idx'
alias wcat='wget -q -O -'
alias v='mvim'
alias vim='mvim -v'
alias cmake='cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc'
alias run='open -a'
alias clearrbc='rm -f */**/*.rbc'
alias dirsizes='du -h -d 1'
