#!/bin/zsh

case $TERM in
    *xterm*|rxvt|rxvt-unicode|rxvt-256color|(dt|k|E)term)
        precmd () { print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~]\a" } 
        preexec () { print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~] ($1)\a" }
    ;;
    screen)
        precmd () { 
            print -Pn "\e]83;title \"$1\"\a" 
            print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~]\a" 
        }
        preexec () { 
            print -Pn "\e]83;title \"$1\"\a" 
            print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~] ($1)\a" 
        }
    ;; 
esac

setprompt () {
    autoload -U colors zsh/terminfo
    colors
    setopt prompt_subst
    PR_NO_COLOR="%{$terminfo[sgr0]%}"
    for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
        eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
        eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
    done

    PROMPT=$'%n${PR_RED}@${PR_NO_COLOR}%m | ${PR_BLUE}%~${PR_NO_COLOR}
${PR_RED}»${PR_NO_COLOR} '
    #RPROMPT=$'${PR_LIGHT_GREEN}%~${PR_NO_COLOR}'
    #export PS1="$(print '%{\e[0;33m%}[%~]%{\e[0;31m%}%#%{\e[0m%} ')"
}

setprompt
