#!/bin/sh

echo '{ "version": 1 }'
echo '['
echo '[],'

while :
do
  #kernel="{\"full_text\": \"KERNEL\", \"color\": \"#676E7D\", \"separator\": false, \"separator_block_width\": 6}, {\"full_text\": \"$(uname -r)\", \"color\": \"#f3f4f5\", \"separator\": false}"
  tztime="{\"full_text\": \"\", \"color\": \"#F9F9F9\", \"separator\": false, \"separator_block_width\": 6}, {\"full_text\": \" $(date +"%a %e %b %H:%M ")\", \"color\": \"#00AAD4\", \"background\": \"#272727\", \"separator\": false}"

  #echo "[$kernel,$tztime]," || exit 1
  echo "[$tztime]," || exit 1
  sleep 53
done
